version: "3"

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443  
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

